version: '3.1'
services:
  card-db:
    image: postgres:14-alpine
    container_name: card-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - card-service-network

  card-service:
    build: cardService/
    container_name: card-service
    depends_on:
      - "card-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://card-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - card-service-network
      - general-network
      
  user-db:
    image: postgres:14-alpine
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - user-service-network

  user-service:
    build: userService/
    container_name: user-service
    depends_on:
      - "user-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - user-service-network
      - general-network
  
  game-service:
    build: gameService/
    networks:
      - general-network

  sale-db:
    image: postgres:14-alpine
    container_name: sale-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - sale-service-network

  sale-service:
    build: saleService/
    container_name: sale-service
    depends_on:
      - "sale-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sale-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - sale-service-network
      - general-network

  reverse-proxy:
    build: reverse-proxy/
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "card-service"
      - "user-service"
      - "sale-service"
      - "static"
    networks:
      - general-network

  static:
    build: web/
    container_name: web
    restart: always
    networks:
      - general-network

networks:
  card-service-network:
  user-service-network:
  sale-service-network:
  general-network:
