version: '3.1'
services:
  card-db:
    image: postgres:14-alpine
    container_name: card-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd

    networks:
      - card-service-network

  card-services:
    build: cardService/
    depends_on:
      - "card-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://card-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - card-service-network
      
  user-db:
    image: postgres:14-alpine
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: bd
    networks:
      - user-service-network

  user-services:
    build: userService/
    depends_on:
      - "user-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/bd
      - SPRING_DATASOURCE_USERNAME=login
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - user-service-network

  reverse-proxy:
    build: reverse-proxy/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - "card-services"
      - "static"
    networks:
      - card-service-network

  static:
    build: web/
    restart: always
    networks:
      - card-service-network

networks:
  card-service-network:
  user-service-network:
